# Generated by Django 6.0.2 on 2026-02-24 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='discounts/%Y/%m/%d'),
        ),
    ]
