# Generated by Django 6.0.2 on 2026-02-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_alter_discount_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='code',
            field=models.CharField(blank=True, default='type_your_promo_code_here', max_length=20, null=True),
        ),
    ]
