# Generated by Django 6.0.2 on 2026-02-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_add_phone_email_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb_link', models.URLField(blank=True, default='https://www.facebook.com/', null=True)),
                ('twitter_link', models.URLField(blank=True, default='https://www.twitter.com/', null=True)),
                ('instagram_link', models.URLField(blank=True, default='https://www.instagram.com/', null=True)),
                ('linkedin_link', models.URLField(blank=True, default='https://www.linkedin.com/', null=True)),
                ('printerest_link', models.URLField(blank=True, default='https://www.pinterest.com/', null=True)),
                ('google_map_link', models.URLField(blank=True, default='https://www.google.com/maps', null=True)),
            ],
            options={
                'verbose_name': 'Social Media Link',
                'verbose_name_plural': 'Social Media Links',
            },
        ),
    ]
