# Generated by Django 6.0.2 on 2026-02-25 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0013_socialmedialink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmedialink',
            name='google_map_link',
        ),
    ]
