# Generated by Django 6.0.2 on 2026-02-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0014_remove_socialmedialink_google_map_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_iframe', models.TextField(blank=True, help_text='Add embedded Google Maps iframe code here', null=True)),
            ],
            options={
                'verbose_name': 'Location Google Map',
                'verbose_name_plural': 'Location Google Maps',
            },
        ),
    ]
