# Generated by Django 6.0.2 on 2026-02-26 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0016_eventtype_tablebooking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tablebooking',
            options={'ordering': ['-date', '-time'], 'verbose_name': 'Table Booking', 'verbose_name_plural': 'Table Bookings'},
        ),
    ]
