# Generated by Django 6.0.2 on 2026-02-26 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0017_alter_tablebooking_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tablebooking',
            options={},
        ),
    ]
