# Generated by Django 6.0.2 on 2026-02-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0018_alter_tablebooking_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_tables', models.PositiveIntegerField(default=20, help_text='Enter the total number of tables available in your restaurant.')),
                ('min_booking_hours', models.PositiveIntegerField(default=2, help_text='How many hours in advance should a customer book?')),
                ('special_notice', models.TextField(blank=True, help_text="Any urgent message (e.g., 'Closed for a private party today').", null=True)),
            ],
            options={
                'verbose_name': 'Restaurant Setting',
                'verbose_name_plural': 'Restaurant Settings',
            },
        ),
    ]
