# Generated by Django 6.0.2 on 2026-02-27 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0019_restaurantsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_phone_email',
            name='location_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
