# Generated by Django 6.0.2 on 2026-02-27 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0021_alter_add_phone_email_location_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_phone_email',
            name='location_link',
            field=models.URLField(default='location_link', max_length=500, unique=True),
            preserve_default=False,
        ),
    ]
